version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    container_name: "redis"
    restart: always

networks:
  default:
    driver: bridge