version: '3.0'

services:
  nginx:
    container_name: php-fpm-7
    image: docker.io/bitnami/php-fpm
    ports:
      - 9000:9000
    volumes:
      - ./data/ng/html:/usr/share/nginx/html

# docker-compose up -d
# docker-compose down
# docker-compose restart