version: '3.0'

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - 81:80
    volumes:
      - ./data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/conf/conf.d:/etc/nginx/conf.d:ro
      - ./data/nginx/html:/usr/share/nginx/html
      - ./data/nginx/logs:/var/log/nginx
    networks:
        lnmp:
          ipv4_address: 10.0.0.10


  php:
      container_name: php
      restart: always
      image: php:7.2-fpm
      ports:
        - 9001:9000
      volumes:
        - ./data/php/php:/usr/local/etc/php:rw
        - ./data/php/php-fpm.d:/usr/local/etc/php-fpm.d:ro
        - ./data/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
        - ./data/php/html:/var/www/html
        - /Users/crystal/codes/php/gitlabcompany:/var/www/html/gitlabcompany
      networks:
        lnmp:
           ipv4_address: 10.0.0.11
      extra_hosts:
        - "sso.yundun.cc:10.0.0.10"
      #command: chmod +x /var/www/html/entrypoint.sh
      #entrypoint: sh /var/www/html/entrypoint.sh

  mysql:
    container_name: mysql
    restart: always
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    volumes:
      - ./data/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./data/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./data/mysql/datadir:/var/lib/mysql
      - ./data/mysql/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_USER: php
#      MYSQL_PASSWORD: 123
#      MYSQL_DATABASE: example
#      MYSQL_ROOT_HOST: '%'
#      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
       lnmp:
         ipv4_address: 10.0.0.12

networks:
  lnmp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24


# docker不能挂载单个文件,nginx.conf需要先docker cp 出来
# docker-compose up -d
# docker-compose down
# docker-compose restart

# docker-compose restart php

# 进入php容器
# docker exec -it php bash

# 安装扩展
# docker-php-ext-install mysqli
# docker-php-ext-install pdo_mysql
# pecl install redis && docker-php-ext-enable redis
# libmemcached
# zlib