version: '3.0'

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - 81:80
    volumes:
      - ./data/ng/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/ng/conf/conf.d:/etc/nginx/conf.d:ro
      - ./data/ng/html:/usr/share/nginx/html
      - ./data/ng/logs:/var/log/nginx
    networks:
      - lnmp

  php:
      #container_name: php-fpm-7.2.23
      container_name: php
      restart: always
      image: php:7.2-fpm
      ports:
        - 9001:9000
      volumes:
        - ./data/php/php:/usr/local/etc/php:rw
        - ./data/php/php-fpm.d:/usr/local/etc/php-fpm.d:ro
        - ./data/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
        - ./data/php/html:/var/www/html
      networks:
        - lnmp
  mysql:
    container_name: mysql
    restart: always
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    volumes:
      - ./data/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./data/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./data/mysql/datadir:/var/lib/mysql
      - ./data/mysql/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_USER: php
#      MYSQL_PASSWORD: 123
#      MYSQL_DATABASE: example
#      MYSQL_ROOT_HOST: '%'
#      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - lnmp
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - lnmp

networks:
  lnmp:


# docker不能挂载单个文件,nginx.conf需要先docker cp 出来
# docker-compose up -d
# docker-compose down
# docker-compose restart